In [50]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [51]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head(20)

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.26540,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.18600,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.24300,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.25750,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.16250,0.2364,0.07678,NaN
5,843786,M,12.45,15.70,82.57,477.1,0.12780,0.17000,0.15780,0.08089,...,23.75,103.40,741.6,0.1791,0.5249,0.5355,0.17410,0.3985,0.12440,NaN
6,844359,M,18.25,19.98,119.60,1040.0,0.09463,0.10900,0.11270,0.07400,...,27.66,153.20,1606.0,0.1442,0.2576,0.3784,0.19320,0.3063,0.08368,NaN
7,84458202,M,13.71,20.83,90.20,577.9,0.11890,0.16450,0.09366,0.05985,...,28.14,110.60,897.0,0.1654,0.3682,0.2678,0.15560,0.3196,0.11510,NaN
8,844981,M,13.00,21.82,87.50,519.8,0.12730,0.19320,0.18590,0.09353,...,30.73,106.20,739.3,0.1703,0.5401,0.5390,0.20600,0.4378,0.10720,NaN
9,84501001,M,12.46,24.04,83.97,475.9,0.11860,0.23960,0.22730,0.08543,...,40.68,97.65,711.4,0.1853,1.0580,1.1050,0.22100,0.4366,0.20750,NaN
10,845636,M,16.02,23.24,102.70,797.8,0.08206,0.06669,0.03299,0.03323,...,33.88,123.80,1150.0,0.1181,0.1551,0.1459,0.09975,0.2948,0.08452,NaN
11,84610002,M,15.78,17.89,103.60,781.0,0.09710,0.12920,0.09954,0.06606,...,27.28,136.50,1299.0,0.1396,0.5609,0.3965,0.18100,0.3792,0.10480,NaN
12,846226,M,19.17,24.80,132.40,1123.0,0.09740,0.24580,0.20650,0.11180,...,29.94,151.70,1332.0,0.1037,0.3903,0.3639,0.17670,0.3176,0.10230,NaN
13,846381,M,15.85,23.95,103.70,782.7,0.08401,0.10020,0.09938,0.05364,...,27.66,112.00,876.5,0.1131,0.1924,0.2322,0.11190,0.2809,0.06287,NaN
14,84667401,M,13.73,22.61,93.60,578.3,0.11310,0.22930,0.21280,0.08025,...,32.01,108.80,697.7,0.1651,0.7725,0.6943,0.22080,0.3596,0.14310,NaN
15,84799002,M,14.54,27.54,96.73,658.8,0.11390,0.15950,0.16390,0.07364,...,37.13,124.10,943.2,0.1678,0.6577,0.7026,0.17120,0.4218,0.13410,NaN
16,848406,M,14.68,20.13,94.74,684.5,0.09867,0.07200,0.07395,0.05259,...,30.88,123.40,1138.0,0.1464,0.1871,0.2914,0.16090,0.3029,0.08216,NaN
17,84862001,M,16.13,20.68,108.10,798.8,0.11700,0.20220,0.17220,0.10280,...,31.48,136.80,1315.0,0.1789,0.4233,0.4784,0.20730,0.3706,0.11420,NaN
18,849014,M,19.81,22.15,130.00,1260.0,0.09831,0.10270,0.14790,0.09498,...,30.88,186.80,2398.0,0.1512,0.3150,0.5372,0.23880,0.2768,0.07615,NaN
19,8510426,B,13.54,14.36,87.46,566.3,0.09779,0.08129,0.06664,0.04781,...,19.26,99.70,711.2,0.1440,0.1773,0.2390,0.12880,0.2977,0.07259,NaN

In [52]:
df.shape

(569, 33)

In [53]:
df.drop(columns=['id','Unnamed: 32'], inplace=True)

In [54]:
df.head(20)

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.26540,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.18600,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.24300,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.25750,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.16250,0.2364,0.07678
5,M,12.45,15.70,82.57,477.1,0.12780,0.17000,0.15780,0.08089,0.2087,...,15.47,23.75,103.40,741.6,0.1791,0.5249,0.5355,0.17410,0.3985,0.12440
6,M,18.25,19.98,119.60,1040.0,0.09463,0.10900,0.11270,0.07400,0.1794,...,22.88,27.66,153.20,1606.0,0.1442,0.2576,0.3784,0.19320,0.3063,0.08368
7,M,13.71,20.83,90.20,577.9,0.11890,0.16450,0.09366,0.05985,0.2196,...,17.06,28.14,110.60,897.0,0.1654,0.3682,0.2678,0.15560,0.3196,0.11510
8,M,13.00,21.82,87.50,519.8,0.12730,0.19320,0.18590,0.09353,0.2350,...,15.49,30.73,106.20,739.3,0.1703,0.5401,0.5390,0.20600,0.4378,0.10720
9,M,12.46,24.04,83.97,475.9,0.11860,0.23960,0.22730,0.08543,0.2030,...,15.09,40.68,97.65,711.4,0.1853,1.0580,1.1050,0.22100,0.4366,0.20750
10,M,16.02,23.24,102.70,797.8,0.08206,0.06669,0.03299,0.03323,0.1528,...,19.19,33.88,123.80,1150.0,0.1181,0.1551,0.1459,0.09975,0.2948,0.08452
11,M,15.78,17.89,103.60,781.0,0.09710,0.12920,0.09954,0.06606,0.1842,...,20.42,27.28,136.50,1299.0,0.1396,0.5609,0.3965,0.18100,0.3792,0.10480
12,M,19.17,24.80,132.40,1123.0,0.09740,0.24580,0.20650,0.11180,0.2397,...,20.96,29.94,151.70,1332.0,0.1037,0.3903,0.3639,0.17670,0.3176,0.10230
13,M,15.85,23.95,103.70,782.7,0.08401,0.10020,0.09938,0.05364,0.1847,...,16.84,27.66,112.00,876.5,0.1131,0.1924,0.2322,0.11190,0.2809,0.06287
14,M,13.73,22.61,93.60,578.3,0.11310,0.22930,0.21280,0.08025,0.2069,...,15.03,32.01,108.80,697.7,0.1651,0.7725,0.6943,0.22080,0.3596,0.14310
15,M,14.54,27.54,96.73,658.8,0.11390,0.15950,0.16390,0.07364,0.2303,...,17.46,37.13,124.10,943.2,0.1678,0.6577,0.7026,0.17120,0.4218,0.13410
16,M,14.68,20.13,94.74,684.5,0.09867,0.07200,0.07395,0.05259,0.1586,...,19.07,30.88,123.40,1138.0,0.1464,0.1871,0.2914,0.16090,0.3029,0.08216
17,M,16.13,20.68,108.10,798.8,0.11700,0.20220,0.17220,0.10280,0.2164,...,20.96,31.48,136.80,1315.0,0.1789,0.4233,0.4784,0.20730,0.3706,0.11420
18,M,19.81,22.15,130.00,1260.0,0.09831,0.10270,0.14790,0.09498,0.1582,...,27.32,30.88,186.80,2398.0,0.1512,0.3150,0.5372,0.23880,0.2768,0.07615
19,B,13.54,14.36,87.46,566.3,0.09779,0.08129,0.06664,0.04781,0.1885,...,15.11,19.26,99.70,711.2,0.1440,0.1773,0.2390,0.12880,0.2977,0.07259

In [55]:
x = df.iloc[: , 1:]
y = df.iloc[: , 0]

x_train, x_test, y_train, y_test  = train_test_split(
    x,y,test_size=0.2, random_state=42
)

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   diagnosis                569 non-null    object
 1   radius_mean              569 non-null    float64
 2   texture_mean             569 non-null    float64
 3   perimeter_mean           569 non-null    float64
 4   area_mean                569 non-null    float64
 5   smoothness_mean          569 non-null    float64
 6   compactness_mean         569 non-null    float64
 7   concavity_mean           569 non-null    float64
 8   concave points_mean      569 non-null    float64
 9   symmetry_mean            569 non-null    float64
 10  fractal_dimension_mean   569 non-null    float64
 11  radius_se                569 non-null    float64
 12  texture_se               569 non-null    float64
 13  perimeter_se             569 non-null    float64
 14  area_se                  569 non-null    float64
 15  smoothness_se            569 non-null    float64
 16  compactness_se           569 non-null    float64
 17  concavity_se             569 non-null    float64
 18  concave points_se        569 non-null    float64
 19  symmetry_se              569 non-null    float64
 20  fractal_dimension_se     569 non-null    float64
 21  radius_worst             569 non-null    float64
 22  texture_worst            569 non-null    float64
 23  perimeter_worst          569 non-null    float64
 24  area_worst               569 non-null    float64
 25  smoothness_worst         569 non-null    float64
 26  compactness_worst        569 non-null    float64
 27  concavity_worst          569 non-null    float64
 28  concave points_worst     569 non-null    float64
 29  symmetry_worst           569 non-null    float64
 30  fractal_dimension_worst  569 non-null    float64
dtypes: float64(30), object(1)
memory usage: 137.9+ KB

In [57]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [58]:
encoder = LabelEncoder()
y_train_encoded = encoder.fit_transform(y_train)
y_test_encoded = encoder.transform(y_test)

In [59]:
type(y_test_encoded)

numpy.ndarray

### Numpy array to tensors conversion

In [60]:
x_train_scaled_tensor = torch.from_numpy(x_train_scaled).float()
x_test_scaled_tensor = torch.from_numpy(x_test_scaled).float()
y_train_encoded_tensor = torch.from_numpy(y_train_encoded).float()
y_test_encoded_tensor = torch.from_numpy(y_test_encoded).float()

In [61]:
type(x_train_scaled_tensor)

torch.Tensor

## Dataset and Dataloader

In [62]:
from torch.utils.data import Dataset , DataLoader

class CustomDataSet(Dataset):
    def __init__(self, features , labels):
        self.features = features
        self.labels = labels
        
    def __len__(self):
        return self.features.shape[0]
    
    def __getitem__(self, index):
        return self.features[index], self.labels[index]

In [63]:
train_dataset = CustomDataSet(x_train_scaled_tensor, y_train_encoded_tensor) 
test_dataset = CustomDataSet(x_test_scaled_tensor, y_test_encoded_tensor)

In [64]:
len(train_dataset)

455

In [65]:
train_dataset[2]

(tensor([-1.4000, -1.2496, -1.3452, -1.1098, -1.3326, -0.3074, -0.3656, -0.6965,
          1.9303,  0.9544,  0.0275,  1.9631, -0.1210, -0.3508,  0.5728,  0.7395,
          0.3207,  0.5895,  2.6150,  0.7189, -1.2953, -1.0408, -1.2452, -0.9997,
         -1.4387, -0.5486, -0.6449, -0.9702,  0.5976,  0.0579]),
 tensor(0.))

In [66]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

In [67]:
x_train_scaled_tensor.shape

torch.Size([455, 30])

### Defining model

In [68]:
# # defining model

# class MysimpleNN():
#     def __init__(self,x):  # for weight and bias
#         self.weights = torch.rand(x.shape[1],1 , dtype=torch.float64, requires_grad=True)
#         self.bias = torch.zeros(1 , dtype=torch.float64 , requires_grad=True)
    
#     def forward(self,x):
#         z = torch.matmul(x,self.weights) + self.bias
#         y_pred = torch.sigmoid(z)
#         return y_pred
    
#     def loss_function(self,y_pred,y):
#         #clump
#         epsilon=1e-7
#         y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
#         loss = -(y_train_encoded_tensor*torch.log(y_pred) + (1-y_train_encoded_tensor)*torch.log(1-y_pred)).mean()
#         return loss

In [69]:
import torch.nn as nn
# defining model

class MysimpleNN(nn.Module):
    def __init__(self,num_features):
        super().__init__()
    
        self.linear = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self,features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out
    
    def loss_function(self,y_pred,y):
        #clump
        epsilon=1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
        loss = -(y_train_encoded_tensor*torch.log(y_pred) + (1-y_train_encoded_tensor)*torch.log(1-y_pred)).mean()
        return loss

In [70]:
model = MysimpleNN(x_train_scaled_tensor.shape[1])
model.linear.weight

Parameter containing:
tensor([[ 0.1330, -0.0736, -0.1299,  0.0955, -0.1582, -0.0665,  0.0374, -0.0953,
          0.0088,  0.1116,  0.0726,  0.0994, -0.0840, -0.1818,  0.0635,  0.1180,
          0.0846,  0.0766,  0.0671, -0.0019,  0.1383,  0.0425, -0.1236,  0.0900,
         -0.0082,  0.0929, -0.0624,  0.0040,  0.1550,  0.1004]],
       requires_grad=True)

In [71]:
model.linear.bias

Parameter containing:
tensor([0.1525], requires_grad=True)

#### Parameters

In [72]:
epochs = 25
learning_rate = 0.1

In [73]:
model.parameters

<bound method Module.parameters of MysimpleNN(
  (linear): Linear(in_features=30, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)>

#### Training pipeline

In [74]:
# create model 
model = MysimpleNN(x_train_scaled_tensor.shape[1])

# optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loop
for epoch in range(epochs):
    
    # forward pass
    y_pred = model(x_train_scaled_tensor) # batch gradient descent
    
    # loss calculate
    loss = model.loss_function(y_pred, y_train_encoded_tensor)
    
    # zero gradient
    # model.linear.weight.grad.zero_()
    # model.linear.bias.grad.zero_()
    optimizer.zero_grad()
    
    # backward pass
    loss.backward()
    
    # parameter update
    # with torch.no_grad():
    #     model.linear.weight -= learning_rate*model.linear.weight.grad
    #     model.linear.bias -= learning_rate*model.linear.bias.grad
    optimizer.step()
        
    # # zero gradient
    # model.linear.weight.grad.zero_()
    # model.linear.bias.grad.zero_()
    
    print(f"{epoch+1}, loss = {loss.item()}")

1, loss = 0.7567082047462463
2, loss = 0.7439761161804199
3, loss = 0.7347754836082458
4, loss = 0.7277991771697998
5, loss = 0.7222580313682556
6, loss = 0.7176799178123474
7, loss = 0.7137786746025085
8, loss = 0.7103748917579651
9, loss = 0.7073519229888916
10, loss = 0.7046303749084473
11, loss = 0.7021540403366089
12, loss = 0.6998815536499023
13, loss = 0.6977819800376892
14, loss = 0.6958311200141907
15, loss = 0.6940104365348816
16, loss = 0.6923050284385681
17, loss = 0.6907027959823608
18, loss = 0.6891937851905823
19, loss = 0.6877701282501221
20, loss = 0.6864244937896729
21, loss = 0.6851513385772705
22, loss = 0.6839455366134644
23, loss = 0.6828024387359619
24, loss = 0.6817182302474976
25, loss = 0.68068927526474

### Training pipeline V2

In [75]:
len(x_train_scaled_tensor)

455

In [76]:
# create model 
# mini batch gradiant descent
model = MysimpleNN(x_train_scaled_tensor.shape[1])

# optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loop
batch_size = 32
epoch = 25
n_sample = len(x_train_scaled_tensor)
for epoch in range(epochs):
    
    for start_indx in range(0, n_sample, batch_size):
        end_indx = start_indx + batch_size
        # print(f'Start index : {start_indx} , End index: {end_indx}')
        
        x_batch = x_train_scaled_tensor[start_indx : end_indx]
        y_batch = y_train_encoded_tensor[start_indx : end_indx]
        
        # forward pass
        y_pred = model(x_batch)
        loss = model.loss_function(y_pred , y_batch.reshape(-1,1))
        
        #update steps
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
    
    print(f"{epoch+1}, loss = {loss.item()}")

1, loss = 0.7005345225334167
2, loss = 0.6793796420097351
3, loss = 0.6697534918785095
4, loss = 0.665115475654602
5, loss = 0.6627959609031677
6, loss = 0.6615918874740601
7, loss = 0.6609406471252441
8, loss = 0.6605721712112427
9, loss = 0.6603532433509827
10, loss = 0.6602162718772888
11, loss = 0.6601262092590332
12, loss = 0.6600639820098877
13, loss = 0.6600192189216614
14, loss = 0.6599853038787842
15, loss = 0.6599591970443726
16, loss = 0.6599382758140564
17, loss = 0.6599209904670715
18, loss = 0.6599064469337463
19, loss = 0.6598939895629883
20, loss = 0.6598832011222839
21, loss = 0.6598735451698303
22, loss = 0.659865140914917
23, loss = 0.659857451915741
24, loss = 0.6598504781723022
25, loss = 0.6598441004753113

### Training pipeline V3

In [77]:
# create model 
model = MysimpleNN(x_train_scaled_tensor.shape[1])

# optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loop
for epoch in range(epochs):
    
    for batch_feature , batch_label in train_loader:
        
        #forward pass
        y_pred = model(batch_feature)
        
        # loss calc
        loss = model.loss_function(y_pred, batch_label.reshape(-1,1))
        
        # zero grad
        optimizer.zero_grad()

        # updates
        loss.backward()
        optimizer.step()
        
    print(f"{epoch+1}, loss = {loss.item()}")

1, loss = 0.7008708715438843
2, loss = 0.6659936308860779
3, loss = 0.673972487449646
4, loss = 0.6632989645004272
5, loss = 0.6628324389457703
6, loss = 0.6610528826713562
7, loss = 0.6601117253303528
8, loss = 0.6621860861778259
9, loss = 0.660775899887085
10, loss = 0.6655653119087219
11, loss = 0.661207377910614
12, loss = 0.6604066491127014
13, loss = 0.6602660417556763
14, loss = 0.6603553891181946
15, loss = 0.6605144739151001
16, loss = 0.6605292558670044
17, loss = 0.6607606410980225
18, loss = 0.6597998142242432
19, loss = 0.6600114703178406
20, loss = 0.6606203317642212
21, loss = 0.6609487533569336
22, loss = 0.6603625416755676
23, loss = 0.6601288318634033
24, loss = 0.6604304909706116
25, loss = 0.6601377725601196

### Evaluation

In [78]:
y_pred = model.forward(x_train_scaled_tensor)  # can't take dicission looking at this
y_pred

tensor([[0.3422],
        [0.3659],
        [0.3832],
        [0.3752],
        [0.3798],
        [0.3889],
        [0.4199],
        [0.3687],
        [0.3725],
        [0.3703],
        [0.3846],
        [0.3797],
        [0.3980],
        [0.3867],
        [0.3774],
        [0.3710],
        [0.3364],
        [0.3684],
        [0.3719],
        [0.3531],
        [0.3700],
        [0.3554],
        [0.3662],
        [0.3651],
        [0.3839],
        [0.3508],
        [0.3614],
        [0.3424],
        [0.3662],
        [0.3747],
        [0.3741],
        [0.3590],
        [0.3666],
        [0.3698],
        [0.3567],
        [0.3603],
        [0.3757],
        [0.3750],
        [0.3668],
        [0.3611],
        [0.3769],
        [0.3758],
        [0.3784],
        [0.3917],
        [0.3739],
        [0.3664],
        [0.3697],
        [0.3699],
        [0.3793],
        [0.3672],
        [0.3748],
        [0.3666],
        [0.3785],
        [0.3628],
        [0.3775],
        [0.4077],
        [0.3728],
        [0.3666],
        [0.3734],
        [0.3462],
        [0.3702],
        [0.3716],
        [0.3623],
        [0.3599],
        [0.3840],
        [0.3832],
        [0.3640],
        [0.3823],
        [0.3654],
        [0.3646],
        [0.3822],
        [0.3735],
        [0.3761],
        [0.3755],
        [0.3706],
        [0.3866],
        [0.3492],
        [0.3585],
        [0.3747],
        [0.3726],
        [0.3750],
        [0.3764],
        [0.3623],
        [0.3913],
        [0.3949],
        [0.3798],
        [0.3671],
        [0.3751],
        [0.3639],
        [0.3692],
        [0.3948],
        [0.3742],
        [0.3689],
        [0.3739],
        [0.3735],
        [0.3429],
        [0.3882],
        [0.3645],
        [0.3692],
        [0.3637],
        [0.3445],
        [0.3363],
        [0.3622],
        [0.3458],
        [0.3590],
        [0.3771],
        [0.3880],
        [0.3672],
        [0.3461],
        [0.3745],
        [0.3659],
        [0.3699],
        [0.3457],
        [0.3728],
        [0.3763],
        [0.3692],
        [0.3613],
        [0.3768],
        [0.3617],
        [0.3577],
        [0.3840],
        [0.3681],
        [0.3947],
        [0.3588],
        [0.3695],
        [0.3580],
        [0.3527],
        [0.3635],
        [0.3800],
        [0.3643],
        [0.3777],
        [0.3308],
        [0.3750],
        [0.3677],
        [0.3608],
        [0.3866],
        [0.3587],
        [0.3680],
        [0.3786],
        [0.3791],
        [0.3600],
        [0.3918],
        [0.3535],
        [0.3730],
        [0.3720],
        [0.3808],
        [0.3739],
        [0.3998],
        [0.3647],
        [0.3606],
        [0.3626],
        [0.3636],
        [0.3710],
        [0.3833],
        [0.3742],
        [0.3468],
        [0.3683],
        [0.3877],
        [0.3716],
        [0.3957],
        [0.3929],
        [0.3771],
        [0.4020],
        [0.3938],
        [0.3709],
        [0.3629],
        [0.3750],
        [0.3565],
        [0.3873],
        [0.3631],
        [0.3695],
        [0.3762],
        [0.3717],
        [0.3775],
        [0.3806],
        [0.3614],
        [0.3589],
        [0.3315],
        [0.3738],
        [0.3644],
        [0.3631],
        [0.3761],
        [0.3687],
        [0.3825],
        [0.3674],
        [0.3907],
        [0.3858],
        [0.3734],
        [0.3572],
        [0.3707],
        [0.3778],
        [0.3922],
        [0.3640],
        [0.3760],
        [0.3655],
        [0.3778],
        [0.3551],
        [0.3890],
        [0.3662],
        [0.3607],
        [0.3584],
        [0.3537],
        [0.3703],
        [0.3767],
        [0.3740],
        [0.3594],
        [0.3690],
        [0.3686],
        [0.3652],
        [0.3678],
        [0.3584],
        [0.3964],
        [0.3902],
        [0.3650],
        [0.3696],
        [0.3900],
        [0.3822],
        [0.3919],
        [0.3949],
        [0.3743],
        [0.3912],
        [0.3721],
        [0.3679],
        [0.3552],
        [0.3533],
        [0.3808],
        [0.3407],
        [0.3541],
        [0.3614],
        [0.3594],
        [0.3731],
        [0.3830],
        [0.3581],
        [0.4112],
        [0.3438],
        [0.3960],
        [0.3589],
        [0.3824],
        [0.3493],
        [0.3716],
        [0.3688],
        [0.3639],
        [0.3729],
        [0.3582],
        [0.3754],
        [0.3785],
        [0.3818],
        [0.3689],
        [0.3683],
        [0.3735],
        [0.3720],
        [0.3633],
        [0.3424],
        [0.4063],
        [0.3553],
        [0.3738],
        [0.3803],
        [0.3785],
        [0.3718],
        [0.3839],
        [0.3707],
        [0.3908],
        [0.3705],
        [0.3516],
        [0.3788],
        [0.3893],
        [0.3849],
        [0.3730],
        [0.3543],
        [0.3806],
        [0.3639],
        [0.3691],
        [0.3643],
        [0.3685],
        [0.3632],
        [0.3641],
        [0.3713],
        [0.3442],
        [0.3547],
        [0.3546],
        [0.3932],
        [0.3780],
        [0.3461],
        [0.3760],
        [0.3661],
        [0.3787],
        [0.3881],
        [0.3752],
        [0.3663],
        [0.3534],
        [0.3647],
        [0.3894],
        [0.3392],
        [0.3610],
        [0.3435],
        [0.3707],
        [0.3597],
        [0.3691],
        [0.3586],
        [0.3571],
        [0.3650],
        [0.3637],
        [0.3808],
        [0.3710],
        [0.3836],
        [0.3520],
        [0.3933],
        [0.3745],
        [0.3717],
        [0.3694],
        [0.3863],
        [0.3844],
        [0.3769],
        [0.3651],
        [0.3706],
        [0.3650],
        [0.3782],
        [0.3864],
        [0.3704],
        [0.3553],
        [0.3832],
        [0.3683],
        [0.3671],
        [0.3810],
        [0.3657],
        [0.3678],
        [0.3459],
        [0.3118],
        [0.3645],
        [0.3643],
        [0.3840],
        [0.3846],
        [0.3602],
        [0.3630],
        [0.3549],
        [0.4060],
        [0.3929],
        [0.3680],
        [0.3591],
        [0.3683],
        [0.3956],
        [0.3662],
        [0.3898],
        [0.3672],
        [0.4011],
        [0.3860],
        [0.3897],
        [0.3856],
        [0.3957],
        [0.3641],
        [0.3646],
        [0.3804],
        [0.4116],
        [0.3951],
        [0.3745],
        [0.3758],
        [0.3724],
        [0.3692],
        [0.3750],
        [0.3680],
        [0.3913],
        [0.3735],
        [0.4003],
        [0.3932],
        [0.3630],
        [0.3913],
        [0.3679],
        [0.3647],
        [0.3660],
        [0.3803],
        [0.3720],
        [0.3697],
        [0.3654],
        [0.3465],
        [0.3426],
        [0.3743],
        [0.4297],
        [0.3620],
        [0.3532],
        [0.3753],
        [0.3719],
        [0.3351],
        [0.3702],
        [0.3744],
        [0.3570],
        [0.3770],
        [0.3609],
        [0.3595],
        [0.3628],
        [0.3743],
        [0.3979],
        [0.3638],
        [0.3715],
        [0.3866],
        [0.3917],
        [0.3541],
        [0.3774],
        [0.4185],
        [0.4089],
        [0.3663],
        [0.3854],
        [0.3588],
        [0.3491],
        [0.3790],
        [0.3746],
        [0.3828],
        [0.3783],
        [0.3657],
        [0.3769],
        [0.3707],
        [0.3881],
        [0.3536],
        [0.3661],
        [0.3784],
        [0.3664],
        [0.3602],
        [0.3799],
        [0.3761],
        [0.3838],
        [0.3731],
        [0.3774],
        [0.3477],
        [0.3822],
        [0.3760],
        [0.3633],
        [0.3766],
        [0.3756],
        [0.3791],
        [0.4120],
        [0.3624],
        [0.3558],
        [0.3791],
        [0.3630],
        [0.3699],
        [0.3902],
        [0.3959],
        [0.3756],
        [0.3699],
        [0.3782],
        [0.3639],
        [0.3698],
        [0.3748],
        [0.3950],
        [0.3688],
        [0.3808],
        [0.3761],
        [0.3821],
        [0.3723],
        [0.3818],
        [0.3349],
        [0.3606],
        [0.3811],
        [0.3679],
        [0.3854],
        [0.3767]], grad_fn=<SigmoidBackward0>)

In [79]:
y_pred = (y_pred>0.9).float()
y_pred

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])

In [80]:
accuracy = (y_pred == y_train_encoded_tensor)
accuracy

tensor([[ True, False,  True,  ...,  True, False,  True],
        [ True, False,  True,  ...,  True, False,  True],
        [ True, False,  True,  ...,  True, False,  True],
        ...,
        [ True, False,  True,  ...,  True, False,  True],
        [ True, False,  True,  ...,  True, False,  True],
        [ True, False,  True,  ...,  True, False,  True]])

In [81]:
accuracy = (y_pred == y_train_encoded_tensor).float()
accuracy

tensor([[1., 0., 1.,  ..., 1., 0., 1.],
        [1., 0., 1.,  ..., 1., 0., 1.],
        [1., 0., 1.,  ..., 1., 0., 1.],
        ...,
        [1., 0., 1.,  ..., 1., 0., 1.],
        [1., 0., 1.,  ..., 1., 0., 1.],
        [1., 0., 1.,  ..., 1., 0., 1.]])

In [82]:
accuracy = (y_pred == y_train_encoded_tensor).float().mean()
accuracy

tensor(0.6286)

In [83]:
with torch.no_grad():
    y_pred = model.forward(x_train_scaled_tensor)  
    y_pred = (y_pred>0.9).float()
    accuracy = (y_pred == y_train_encoded_tensor).float().mean()
    print(accuracy)

tensor(0.6286)

### Evaluation v2

In [84]:
y_pred.shape

torch.Size([455, 1])

In [85]:
batch_label.shape

torch.Size([7])

In [93]:
model.eval() # evaluation mode
accuracy_list = []

with torch.no_grad():
    for batch_feature, batch_label in test_loader:
        y_pred = model(batch_feature)  
        y_pred = (y_pred>0.9).float()
        
        # .view(-1) to match shape with label
        batch_accuracy = (y_pred.view(-1) == batch_label).float().mean()
        accuracy_list.append(batch_accuracy)

overallaccuracy = sum(accuracy_list)/ len(accuracy_list)
print(overallaccuracy)

tensor(0.6215)

In [87]:
accuracy_list

[tensor(0.7500), tensor(0.5625), tensor(0.5312), tensor(0.6667)]

In [94]:
# summary
from torchinfo import summary
summary(model,input_size=(455,30))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
MysimpleNN                               [455, 1]                  --
├─Linear: 1-1                            [455, 1]                  31
├─Sigmoid: 1-2                           [455, 1]                  --
==========================================================================================
Total params: 31
Trainable params: 31
Non-trainable params: 0
Total mult-adds (M): 0.01
==========================================================================================
Input size (MB): 0.05
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.06
==========================================================================================