In [5]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [6]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head(20)

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.26540,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.18600,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.24300,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.25750,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.16250,0.2364,0.07678,NaN
5,843786,M,12.45,15.70,82.57,477.1,0.12780,0.17000,0.15780,0.08089,...,23.75,103.40,741.6,0.1791,0.5249,0.5355,0.17410,0.3985,0.12440,NaN
6,844359,M,18.25,19.98,119.60,1040.0,0.09463,0.10900,0.11270,0.07400,...,27.66,153.20,1606.0,0.1442,0.2576,0.3784,0.19320,0.3063,0.08368,NaN
7,84458202,M,13.71,20.83,90.20,577.9,0.11890,0.16450,0.09366,0.05985,...,28.14,110.60,897.0,0.1654,0.3682,0.2678,0.15560,0.3196,0.11510,NaN
8,844981,M,13.00,21.82,87.50,519.8,0.12730,0.19320,0.18590,0.09353,...,30.73,106.20,739.3,0.1703,0.5401,0.5390,0.20600,0.4378,0.10720,NaN
9,84501001,M,12.46,24.04,83.97,475.9,0.11860,0.23960,0.22730,0.08543,...,40.68,97.65,711.4,0.1853,1.0580,1.1050,0.22100,0.4366,0.20750,NaN
10,845636,M,16.02,23.24,102.70,797.8,0.08206,0.06669,0.03299,0.03323,...,33.88,123.80,1150.0,0.1181,0.1551,0.1459,0.09975,0.2948,0.08452,NaN
11,84610002,M,15.78,17.89,103.60,781.0,0.09710,0.12920,0.09954,0.06606,...,27.28,136.50,1299.0,0.1396,0.5609,0.3965,0.18100,0.3792,0.10480,NaN
12,846226,M,19.17,24.80,132.40,1123.0,0.09740,0.24580,0.20650,0.11180,...,29.94,151.70,1332.0,0.1037,0.3903,0.3639,0.17670,0.3176,0.10230,NaN
13,846381,M,15.85,23.95,103.70,782.7,0.08401,0.10020,0.09938,0.05364,...,27.66,112.00,876.5,0.1131,0.1924,0.2322,0.11190,0.2809,0.06287,NaN
14,84667401,M,13.73,22.61,93.60,578.3,0.11310,0.22930,0.21280,0.08025,...,32.01,108.80,697.7,0.1651,0.7725,0.6943,0.22080,0.3596,0.14310,NaN
15,84799002,M,14.54,27.54,96.73,658.8,0.11390,0.15950,0.16390,0.07364,...,37.13,124.10,943.2,0.1678,0.6577,0.7026,0.17120,0.4218,0.13410,NaN
16,848406,M,14.68,20.13,94.74,684.5,0.09867,0.07200,0.07395,0.05259,...,30.88,123.40,1138.0,0.1464,0.1871,0.2914,0.16090,0.3029,0.08216,NaN
17,84862001,M,16.13,20.68,108.10,798.8,0.11700,0.20220,0.17220,0.10280,...,31.48,136.80,1315.0,0.1789,0.4233,0.4784,0.20730,0.3706,0.11420,NaN
18,849014,M,19.81,22.15,130.00,1260.0,0.09831,0.10270,0.14790,0.09498,...,30.88,186.80,2398.0,0.1512,0.3150,0.5372,0.23880,0.2768,0.07615,NaN
19,8510426,B,13.54,14.36,87.46,566.3,0.09779,0.08129,0.06664,0.04781,...,19.26,99.70,711.2,0.1440,0.1773,0.2390,0.12880,0.2977,0.07259,NaN

In [7]:
df.shape

(569, 33)

In [8]:
df.drop(columns=['id','Unnamed: 32'], inplace=True)

In [9]:
df.head(20)

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.26540,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.18600,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.24300,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.25750,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.16250,0.2364,0.07678
5,M,12.45,15.70,82.57,477.1,0.12780,0.17000,0.15780,0.08089,0.2087,...,15.47,23.75,103.40,741.6,0.1791,0.5249,0.5355,0.17410,0.3985,0.12440
6,M,18.25,19.98,119.60,1040.0,0.09463,0.10900,0.11270,0.07400,0.1794,...,22.88,27.66,153.20,1606.0,0.1442,0.2576,0.3784,0.19320,0.3063,0.08368
7,M,13.71,20.83,90.20,577.9,0.11890,0.16450,0.09366,0.05985,0.2196,...,17.06,28.14,110.60,897.0,0.1654,0.3682,0.2678,0.15560,0.3196,0.11510
8,M,13.00,21.82,87.50,519.8,0.12730,0.19320,0.18590,0.09353,0.2350,...,15.49,30.73,106.20,739.3,0.1703,0.5401,0.5390,0.20600,0.4378,0.10720
9,M,12.46,24.04,83.97,475.9,0.11860,0.23960,0.22730,0.08543,0.2030,...,15.09,40.68,97.65,711.4,0.1853,1.0580,1.1050,0.22100,0.4366,0.20750
10,M,16.02,23.24,102.70,797.8,0.08206,0.06669,0.03299,0.03323,0.1528,...,19.19,33.88,123.80,1150.0,0.1181,0.1551,0.1459,0.09975,0.2948,0.08452
11,M,15.78,17.89,103.60,781.0,0.09710,0.12920,0.09954,0.06606,0.1842,...,20.42,27.28,136.50,1299.0,0.1396,0.5609,0.3965,0.18100,0.3792,0.10480
12,M,19.17,24.80,132.40,1123.0,0.09740,0.24580,0.20650,0.11180,0.2397,...,20.96,29.94,151.70,1332.0,0.1037,0.3903,0.3639,0.17670,0.3176,0.10230
13,M,15.85,23.95,103.70,782.7,0.08401,0.10020,0.09938,0.05364,0.1847,...,16.84,27.66,112.00,876.5,0.1131,0.1924,0.2322,0.11190,0.2809,0.06287
14,M,13.73,22.61,93.60,578.3,0.11310,0.22930,0.21280,0.08025,0.2069,...,15.03,32.01,108.80,697.7,0.1651,0.7725,0.6943,0.22080,0.3596,0.14310
15,M,14.54,27.54,96.73,658.8,0.11390,0.15950,0.16390,0.07364,0.2303,...,17.46,37.13,124.10,943.2,0.1678,0.6577,0.7026,0.17120,0.4218,0.13410
16,M,14.68,20.13,94.74,684.5,0.09867,0.07200,0.07395,0.05259,0.1586,...,19.07,30.88,123.40,1138.0,0.1464,0.1871,0.2914,0.16090,0.3029,0.08216
17,M,16.13,20.68,108.10,798.8,0.11700,0.20220,0.17220,0.10280,0.2164,...,20.96,31.48,136.80,1315.0,0.1789,0.4233,0.4784,0.20730,0.3706,0.11420
18,M,19.81,22.15,130.00,1260.0,0.09831,0.10270,0.14790,0.09498,0.1582,...,27.32,30.88,186.80,2398.0,0.1512,0.3150,0.5372,0.23880,0.2768,0.07615
19,B,13.54,14.36,87.46,566.3,0.09779,0.08129,0.06664,0.04781,0.1885,...,15.11,19.26,99.70,711.2,0.1440,0.1773,0.2390,0.12880,0.2977,0.07259

In [10]:
x = df.iloc[: , 1:]
y = df.iloc[: , 0]

x_train, x_test, y_train, y_test  = train_test_split(
    x,y,test_size=0.2, random_state=42
)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   diagnosis                569 non-null    object
 1   radius_mean              569 non-null    float64
 2   texture_mean             569 non-null    float64
 3   perimeter_mean           569 non-null    float64
 4   area_mean                569 non-null    float64
 5   smoothness_mean          569 non-null    float64
 6   compactness_mean         569 non-null    float64
 7   concavity_mean           569 non-null    float64
 8   concave points_mean      569 non-null    float64
 9   symmetry_mean            569 non-null    float64
 10  fractal_dimension_mean   569 non-null    float64
 11  radius_se                569 non-null    float64
 12  texture_se               569 non-null    float64
 13  perimeter_se             569 non-null    float64
 14  area_se                  569 non-null    float64
 15  smoothness_se            569 non-null    float64
 16  compactness_se           569 non-null    float64
 17  concavity_se             569 non-null    float64
 18  concave points_se        569 non-null    float64
 19  symmetry_se              569 non-null    float64
 20  fractal_dimension_se     569 non-null    float64
 21  radius_worst             569 non-null    float64
 22  texture_worst            569 non-null    float64
 23  perimeter_worst          569 non-null    float64
 24  area_worst               569 non-null    float64
 25  smoothness_worst         569 non-null    float64
 26  compactness_worst        569 non-null    float64
 27  concavity_worst          569 non-null    float64
 28  concave points_worst     569 non-null    float64
 29  symmetry_worst           569 non-null    float64
 30  fractal_dimension_worst  569 non-null    float64
dtypes: float64(30), object(1)
memory usage: 137.9+ KB

In [12]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [13]:
encoder = LabelEncoder()
y_train_encoded = encoder.fit_transform(y_train)
y_test_encoded = encoder.transform(y_test)

In [14]:
type(y_test_encoded)

numpy.ndarray

### Numpy array to tensors conversion

In [15]:
x_train_scaled_tensor = torch.from_numpy(x_train_scaled)
x_test_scaled_tensor = torch.from_numpy(x_test_scaled)
y_train_encoded_tensor = torch.from_numpy(y_train_encoded)
x_test_encoded_tensor = torch.from_numpy(y_test_encoded)

In [16]:
type(x_train_scaled_tensor)

torch.Tensor

In [17]:
x_train_scaled_tensor.shape

torch.Size([455, 30])

In [18]:
# defining model

class MysimpleNN():
    def __init__(self,x):  # for weight and bias
        self.weights = torch.rand(x.shape[1],1 , dtype=torch.float64, requires_grad=True)
        self.bias = torch.zeros(1 , dtype=torch.float64 , requires_grad=True)
    
    def forward(self,x):
        z = torch.matmul(x,self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    
    def loss_function(self,y_pred,y):
        #clump
        epsilon=1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
        loss = -(y_train_encoded_tensor*torch.log(y_pred) + (1-y_train_encoded_tensor)*torch.log(1-y_pred)).mean()
        return loss

In [19]:
model = MysimpleNN(x_train_scaled_tensor)
model.weights

tensor([[0.0901],
        [0.4351],
        [0.7116],
        [0.7177],
        [0.2040],
        [0.6079],
        [0.4840],
        [0.6265],
        [0.5851],
        [0.3280],
        [0.2784],
        [0.5399],
        [0.5949],
        [0.8875],
        [0.1992],
        [0.0621],
        [0.6649],
        [0.1615],
        [0.3595],
        [0.8281],
        [0.4983],
        [0.8187],
        [0.4579],
        [0.3487],
        [0.4729],
        [0.3369],
        [0.4271],
        [0.0593],
        [0.9270],
        [0.9005]], dtype=torch.float64, requires_grad=True)

In [20]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

#### Parameters

In [ ]:
epochs = 25
learning_rate = 0.1

#### Training pipeline

In [28]:
# create model 
model = MysimpleNN(x_train_scaled_tensor)

# define loop
for epoch in range(epochs):
    
    # forward pass
    y_pred = model.forward(x_train_scaled_tensor)
    
    # loss calculate
    loss = model.loss_function(y_pred, y_train_encoded_tensor)
    
    # backward pass
    loss.backward()
    
    # parameter update
    with torch.no_grad():
        model.weights -= learning_rate*model.weights.grad
        model.bias -= learning_rate*model.bias.grad
        
    # zero gradient
    model.weights.grad.zero_()
    model.bias.grad.zero_()
    
    print(f"{epoch+1}, loss = {loss.item()}")

1, loss = 3.807621082761883
2, loss = 3.6841421800721923
3, loss = 3.5589368970334236
4, loss = 3.4317162833506254
5, loss = 3.3022562141847405
6, loss = 3.1674454661345766
7, loss = 3.027517004774677
8, loss = 2.883579675364517
9, loss = 2.7328101341069218
10, loss = 2.579530057280985
11, loss = 2.4269125889877037
12, loss = 2.2735857921296416
13, loss = 2.116623690344051
14, loss = 1.9607909606058835
15, loss = 1.8076648573331695
16, loss = 1.6534535018932712
17, loss = 1.5097127820725957
18, loss = 1.3742676279829609
19, loss = 1.2529291438382346
20, loss = 1.1469603952482688
21, loss = 1.0570954332598768
22, loss = 0.9832806154988973
23, loss = 0.9245251258717412
24, loss = 0.8789765960594006
25, loss = 0.8442581131715466

In [31]:
y_pred = model.forward(x_train_scaled_tensor)  # can't take dicission looking at this
y_pred

tensor([[0.9730],
        [0.5630],
        [0.9661],
        [0.3205],
        [0.8829],
        [0.6621],
        [0.4374],
        [0.2289],
        [0.4469],
        [0.4328],
        [0.5366],
        [0.3879],
        [0.5239],
        [0.6421],
        [0.2084],
        [0.4376],
        [0.9189],
        [0.7144],
        [0.2594],
        [0.4386],
        [0.1946],
        [0.7622],
        [0.3068],
        [0.8611],
        [0.4001],
        [0.2213],
        [0.2853],
        [0.3074],
        [0.2883],
        [0.2044],
        [0.5369],
        [0.4587],
        [0.2372],
        [0.4732],
        [0.2265],
        [0.1865],
        [0.1684],
        [0.4213],
        [0.3857],
        [0.2735],
        [0.1756],
        [0.9216],
        [0.5946],
        [0.3703],
        [0.2046],
        [0.3047],
        [0.9962],
        [0.7413],
        [0.5873],
        [0.5172],
        [0.3995],
        [0.6705],
        [0.2488],
        [0.2865],
        [0.8626],
        [0.6757],
        [0.4983],
        [0.1905],
        [0.3991],
        [0.8884],
        [0.3287],
        [0.2914],
        [0.2643],
        [0.3232],
        [0.4294],
        [0.2298],
        [0.4753],
        [0.3047],
        [0.3675],
        [0.6561],
        [0.7190],
        [0.7075],
        [0.3952],
        [0.3314],
        [0.5427],
        [0.5821],
        [0.5173],
        [0.1757],
        [0.4327],
        [0.5476],
        [0.6940],
        [0.1622],
        [0.2511],
        [0.3796],
        [0.8384],
        [0.3365],
        [0.2651],
        [0.8135],
        [0.9042],
        [0.2389],
        [0.4234],
        [0.6092],
        [0.3048],
        [0.3104],
        [0.4288],
        [0.2172],
        [0.4421],
        [0.7179],
        [0.6216],
        [0.8475],
        [0.8706],
        [0.7843],
        [0.2628],
        [0.7715],
        [0.5022],
        [0.7674],
        [0.4041],
        [0.2933],
        [0.4129],
        [0.5959],
        [0.4804],
        [0.6071],
        [0.7479],
        [0.5670],
        [0.3371],
        [0.2207],
        [0.4862],
        [0.2795],
        [0.9242],
        [0.3262],
        [0.4460],
        [0.3968],
        [0.4434],
        [0.4794],
        [0.2706],
        [0.2629],
        [0.3842],
        [0.3267],
        [0.3082],
        [0.2860],
        [0.6482],
        [0.4904],
        [0.4811],
        [0.2218],
        [0.1930],
        [0.3249],
        [0.4734],
        [0.2811],
        [0.2775],
        [0.3851],
        [0.5301],
        [0.9401],
        [0.4962],
        [0.6374],
        [0.4272],
        [0.5029],
        [0.3039],
        [0.6194],
        [0.6594],
        [0.6718],
        [0.3199],
        [0.2110],
        [0.4951],
        [0.5112],
        [0.3360],
        [0.2548],
        [0.2735],
        [0.2712],
        [0.3673],
        [0.4887],
        [0.2921],
        [0.1793],
        [0.7149],
        [0.9909],
        [0.5906],
        [0.9250],
        [0.1820],
        [0.4557],
        [0.3988],
        [0.6691],
        [0.3041],
        [0.3197],
        [0.3547],
        [0.4739],
        [0.4248],
        [0.2393],
        [0.3112],
        [0.1525],
        [0.3320],
        [0.5055],
        [0.3235],
        [0.6469],
        [0.6330],
        [0.4226],
        [0.3459],
        [0.2019],
        [0.4693],
        [0.4875],
        [0.6787],
        [0.3419],
        [0.2608],
        [0.5650],
        [0.2748],
        [0.6506],
        [0.6614],
        [0.5619],
        [0.7546],
        [0.6329],
        [0.4690],
        [0.7407],
        [0.3607],
        [0.9563],
        [0.8416],
        [0.2456],
        [0.7192],
        [0.1238],
        [0.5330],
        [0.4037],
        [0.5984],
        [0.5842],
        [0.3281],
        [0.0741],
        [0.5343],
        [0.5967],
        [0.3299],
        [0.7278],
        [0.3898],
        [0.3437],
        [0.9952],
        [0.3111],
        [0.5913],
        [0.4795],
        [0.5235],
        [0.2947],
        [0.2437],
        [0.8060],
        [0.5131],
        [0.7462],
        [0.5973],
        [0.2625],
        [0.2637],
        [0.4062],
        [0.4294],
        [0.6528],
        [0.2018],
        [0.4968],
        [0.3442],
        [0.4710],
        [0.2277],
        [0.5118],
        [0.5110],
        [0.3941],
        [0.4142],
        [0.2314],
        [0.3167],
        [0.3734],
        [0.2690],
        [0.7137],
        [0.4173],
        [0.4694],
        [0.9191],
        [0.5686],
        [0.9866],
        [0.9564],
        [0.8618],
        [0.2176],
        [0.2165],
        [0.4051],
        [0.3643],
        [0.2244],
        [0.5781],
        [0.4990],
        [0.4598],
        [0.9683],
        [0.2020],
        [0.2619],
        [0.2712],
        [0.2644],
        [0.7881],
        [0.2498],
        [0.6490],
        [0.3117],
        [0.2038],
        [0.5797],
        [0.7326],
        [0.4989],
        [0.4215],
        [0.9407],
        [0.1819],
        [0.6954],
        [0.6025],
        [0.2838],
        [0.2449],
        [0.1449],
        [0.2856],
        [0.3003],
        [0.4358],
        [0.6834],
        [0.9141],
        [0.1160],
        [0.2674],
        [0.2364],
        [0.9707],
        [0.2645],
        [0.3517],
        [0.3144],
        [0.5285],
        [0.4157],
        [0.3660],
        [0.3717],
        [0.3244],
        [0.3598],
        [0.6754],
        [0.2378],
        [0.2446],
        [0.2345],
        [0.8877],
        [0.5821],
        [0.1768],
        [0.5637],
        [0.3631],
        [0.3790],
        [0.6243],
        [0.3961],
        [0.6234],
        [0.3080],
        [0.7113],
        [0.3748],
        [0.2371],
        [0.4446],
        [0.5651],
        [0.4576],
        [0.4702],
        [0.5663],
        [0.2335],
        [0.2792],
        [0.3434],
        [0.4352],
        [0.4903],
        [0.2808],
        [0.3747],
        [0.3737],
        [0.6454],
        [0.6662],
        [0.2525],
        [0.4968],
        [0.5760],
        [0.8147],
        [0.5329],
        [0.2529],
        [0.4196],
        [0.3846],
        [0.7657],
        [0.5011],
        [0.2971],
        [0.1762],
        [0.2889],
        [0.8878],
        [0.3267],
        [0.4925],
        [0.8721],
        [0.3194],
        [0.8539],
        [0.7926],
        [0.3190],
        [0.3625],
        [0.1976],
        [0.4326],
        [0.2957],
        [0.3935],
        [0.3797],
        [0.7280],
        [0.6425],
        [0.5628],
        [0.1851],
        [0.8126],
        [0.1883],
        [0.7280],
        [0.6139],
        [0.5295],
        [0.3622],
        [0.3308],
        [0.2667],
        [0.7161],
        [0.5766],
        [0.3046],
        [0.9822],
        [0.2337],
        [0.6166],
        [0.3012],
        [0.1982],
        [0.9063],
        [0.1934],
        [0.2164],
        [0.3704],
        [0.2744],
        [0.4172],
        [0.2361],
        [0.3286],
        [0.1764],
        [0.4393],
        [0.3587],
        [0.7836],
        [0.3420],
        [0.9525],
        [0.2353],
        [0.2426],
        [0.3113],
        [0.5978],
        [0.8578],
        [0.4047],
        [0.2950],
        [0.7546],
        [0.2320],
        [0.4656],
        [0.2205],
        [0.5262],
        [0.2052],
        [0.6835],
        [0.3301],
        [0.3682],
        [0.9223],
        [0.1816],
        [0.3266],
        [0.1245],
        [0.2496],
        [0.6781],
        [0.2660],
        [0.5627],
        [0.3360],
        [0.2592],
        [0.6983],
        [0.2736],
        [0.2834],
        [0.2415],
        [0.3681],
        [0.4473],
        [0.4402],
        [0.7398],
        [0.5584],
        [0.2717],
        [0.2585],
        [0.6392],
        [0.5755],
        [0.6244],
        [0.3383],
        [0.4755],
        [0.3046],
        [0.7639],
        [0.1819],
        [0.3717],
        [0.6380],
        [0.5677],
        [0.2762],
        [0.1724],
        [0.3914],
        [0.8095],
        [0.3082],
        [0.7384],
        [0.3551],
        [0.5046],
        [0.4912],
        [0.2049],
        [0.2823],
        [0.3418]], dtype=torch.float64, grad_fn=<SigmoidBackward0>)

In [33]:
y_pred = (y_pred>0.9).float()
y_pred

tensor([[1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])

In [36]:
accuracy = (y_pred == y_train_encoded_tensor)
accuracy

tensor([[False,  True, False,  ..., False,  True, False],
        [ True, False,  True,  ...,  True, False,  True],
        [False,  True, False,  ..., False,  True, False],
        ...,
        [ True, False,  True,  ...,  True, False,  True],
        [ True, False,  True,  ...,  True, False,  True],
        [ True, False,  True,  ...,  True, False,  True]])

In [37]:
accuracy = (y_pred == y_train_encoded_tensor).float()
accuracy

tensor([[0., 1., 0.,  ..., 0., 1., 0.],
        [1., 0., 1.,  ..., 1., 0., 1.],
        [0., 1., 0.,  ..., 0., 1., 0.],
        ...,
        [1., 0., 1.,  ..., 1., 0., 1.],
        [1., 0., 1.,  ..., 1., 0., 1.],
        [1., 0., 1.,  ..., 1., 0., 1.]])

In [38]:
accuracy = (y_pred == y_train_encoded_tensor).float().mean()
accuracy

tensor(0.6156)

In [39]:
with torch.no_grad():
    y_pred = model.forward(x_train_scaled_tensor)  
    y_pred = (y_pred>0.9).float()
    accuracy = (y_pred == y_train_encoded_tensor).float().mean()
    print(accuracy)

tensor(0.6156)